[project]
name = "madisonlogic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "meilisearch>=0.38.0",
    "pandas>=2.3.3",
]
