[project]
name = "madisonlogic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.21",
    "meilisearch>=0.38.0",
    "meilisearch-python-sdk>=5.7.0",
    "pandas>=2.3.3",
]
